### ISSUE TITLE
D3D12 Shader Debugging tracking issue

### ISSUE THREAD

**Issue by skarolewics** [baldurk/renderdoc#1771]
## Description

With RenderDoc v1.7, D3D12 shader debugging is available for preview, for shaders compiled with FXC (shader model 5.1 or earlier). This issue tracks any known problems or missing features to match feature parity with D3D11 shader debugging (for VS, PS, CS), with an aim of stabilizing it enough to ship in an official build.

**_NOTE: Support for shader model 6.0+ and DXIL is not within the scope of this tracking issue, but discussion of it can be found here: #1718_** 

**Any help testing out real scenarios and reporting issues here would be greatly appreciated.** To enable D3D12 shader debugging:
For RenderDoc v1.7, or builds prior to d408f77241710a222106fd9577dff924f3fbc23a:
1. Open `%APPDATA%/qrenderdoc/UI.config`
2. Find the `"ConfigSettings"` section.
3. Add a new entry: `"d3d12ShaderDebugging": "true"`

For builds after d408f77241710a222106fd9577dff924f3fbc23a:
1. Launch RenderDoc
2. Open the `Settings` window (`Tools -> Settings`)
3. Select the `Core` section and then click the `Config Editor` button
4. Expand the `D3D12` section and check the `ShaderDebugging` checkbox.

The below items are known issues as of RenderDoc v1.7. Any items marked completed should be fixed in a more recent nightly build.
- [ ] More general testing is needed to identify bugs
- [X] Resource arrays do not properly display in the texture viewer or shader viewer.
- [X] Indexing with NonUniformResourceIndex does not work
- [x] Unbounded resources in HLSL do not display in shader viewer
- [x] Certain shader linkage scenarios can cause pixel shader debugging to fail. A case identified had `float2 val1 : TEXCOORD0` followed by `float val2 : TEXCOORD1`, with the latter value unreferenced by the pixel shader.

## Environment
- RenderDoc build: Latest HEAD code
- Operating System: Windows
- API: D3D12
