### ISSUE TITLE
Vulkan Shader Debugging tracking issue

### ISSUE THREAD

**Issue by baldurk** [baldurk/renderdoc#1908]
## Description

As of RenderDoc v1.9 vulkan shader debugging is a supported stable feature, and can be used straight away. This meta-issue tracks any remaining work needed to improve support.

If you run into problems with the pixel history feature please reply on this issue with a clear description of the problem and **provide a reproducible test case**. If you can't publicly share a capture, you can contact baldurk@baldurk.org privately to share it.

**NOTE: Please install the latest drivers available before testing as there have been some relevant bug fixes in multiple drivers. For nvidia drivers 451.48 is the first stable driver that works, previous versions have a bug which causes pixel shader debugging to fail. Install 451.48 or newer, or else the latest [beta developer driver](https://developer.nvidia.com/vulkan-driver) to fix this.**

## Current Status

Tracking known issues here, as well as features which are currently lacking:

* [ ] Better use of debug information. Currently the debugging is primarily at SPIR-V level, not source language level.
* [x] Support for different bit-widths, including Int8/Int16/Int64 and Float16/Float64.
* [ ] Support for variable pointers and buffer device address physical pointers.
* [ ] Support for group/subgroup operations.

## Environment

* RenderDoc version: v1.9 or later stable build
* Operating System: Windows, Linux, Android
* Graphics API: Vulkan
* Graphics Driver: Latest available.

**Comment by godlikepanos** [comment]
Hi,

## Description

I recently bumped into an issue while using the debugger. It seems that global variables which their values derive from spec constants are not properly initialized.

```
const uint _anki_const_0_2_FB_SIZE = 1 : [[SpecId(0)]];
const uint FB_SIZE_X = _anki_const_0_2_FB_SIZE + 0;
const uint _anki_const_1_2_FB_SIZE = 1 : [[SpecId(1)]];
const uint FB_SIZE_Y = _anki_const_1_2_FB_SIZE + 0;
const uint2 FB_SIZE = {FB_SIZE_X, FB_SIZE_Y};
```
The snipet above is from a compute shader that exhibits this issue. The shader's main() is using the `FB_SIZE` which the debugger thinks it's zero. Replacing the `FB_SIZE` with the actual spec constants works fine so something probably went wrong with the initialization of `FB_SIZE`. I'm not yet sure if this is an issue with global variables in general.

## Steps to reproduce

This is a renderdoc capture. The compute shader in question is used by the 3rd dispatch job:

https://drive.google.com/file/d/1oOBu6k3UeylRRp9-Sgm2vx8L4eeAgLsj/view?usp=sharing

## Environment

* RenderDoc version: 18689e3b892803e828130e521906ad87ca185145 
* Operating System: Ubuntu 20.04
* Graphics API: Vulkan
* Graphics Driver: Mesa 20.0.8 (not that it matters in my case)

**Comment by baldurk** [comment]
That commit should fix the issue, composite spec constants weren't being re-evaluated with the debugged pipeline's spec constant data.

**Comment by frguthmann** [comment]
Hello,

## Description
The debugger does not seem to recognize the variable `gl_WorkGroupSize`. 

### Steps to reproduce
Start debugging a compute shader in RenderDoc and mouse over the variable `gl_WorkGroupSize`. Nothing appears.
Also, adding this variable to the watch yields the following message: _Couldn't find variable 'gl_WorkGroupSize'_. 

I have not tried this with the latest commit, only v1.9.

## Environment

RenderDoc version: 1.9
Operating System: Windows 10
Graphics API: Vulkan
Graphics Driver: Nvidia 452.06

**Comment by baldurk** [comment]
As listed in the main issue description in general source-level debugging is not currently supported, only direct debugging of the SPIR-V. If you do not have a SPIR-V variable that is named `gl_WorkGroupSize` then it will not be listed as a variable nor show up with any tooltip.

Please provide **complete** steps to reproduce, at minimum sharing such a shader if not a capture that shows the problem.

**Comment by frguthmann** [comment]
Ok I see, sorry. I was surprised because all the other builtin worked. Turns out the SPIR-V looks like this, weird.
```
const uint3 _14 = {_10, _11, 1} : [[BuiltIn(WorkgroupSize)]];
Input uint3* gl_NumWorkGroups : [[BuiltIn(NumWorkgroups)]];
```

[compute.zip](https://github.com/baldurk/renderdoc/files/5125335/compute.zip)

**Comment by baldurk** [comment]
It seems glslang hasn't given a name to the constant 14 that represents `gl_WorkGroupSize`, possibly because it is a constant (specialization constant in this case) and not an actual variable. That is why it isn't recognised by RenderDoc's debugger currently though, because the SPIR-V gives no explicit indication that the constant with ID 14 is named `gl_WorkGroupSize`.

It might be a glslang change you could request to improve legibility of the SPIR-V and to have the name work as with the other builtins in this case.

**Comment by frguthmann** [comment]
Yes that makes sense. Thanks for the suggestion but I don't need it to work, I can just look at the specialization constants. I only meant to help because this tool is invaluable.

**Comment by Mrkol** [comment]
Any plans on implementing source-level debugging in the nearest future? If someone who knows the codebase well could create an issue with pointers on how to tackle implementing this, that'd be great

**Comment by baldurk** [comment]
That is dependent mostly on getting good debug information into the SPIR-V, the large majority of the work is in the compilation toolchain and not in RenderDoc itself. It is planned as can be seen in the first item in the original issue description.

**Comment by Mrkol** [comment]
By the way, I have recently noticed a problem with compute shader debugging. When I try to debug any thread but the (0, 0, 0)th in a workgroup, renderdoc thinks for a couple of seconds and then crashes. This reproduces pretty reliably with [this](https://github.com/Mrkol/vk_graphics_basic/tree/3884fe88269fcc6a3b9ab8b60f625e51d4a2c4ff/src/samples/simpleforward) project with the culling compute shader. Is this a known issue, or should I create a new one and gather some additional info?

**Comment by baldurk** [comment]
If you encounter bugs while using the vulkan shader debugging then please open a new issue with a reproducible test case. This issue is not intended to be a catch-all for every possible bug related to vulkan shader debugging.

In fact these tracking issues should just be closed since the feature is no longer new/in beta.
