### ISSUE TITLE
Vulkan Pixel History tracking issue 

### ISSUE THREAD

**Issue by apazylbe** [baldurk/renderdoc#1910]
## Description

As of RenderDoc v1.9 vulkan pixel history is a supported stable feature, and can be used straight away. This meta-issue tracks any remaining work needed to improve support.

If you run into problems with the pixel history feature please reply on this issue with a clear description of the problem and provide a reproducible test case. If you can't publicly share a capture, you can contact baldurk@baldurk.org privately to share it.

## Current Status

Tracking known limitations:

- [ ] Support for early fragment tests mode in fragment shader (currently might cause incorrect reporting of shader discard)
- [ ] Fragment counts include fragments that failed the depth test, if any fragments were drawn
- [ ] Support for different image subresource ranges used to access pixel history image target
- [ ] Command buffer re-submission is not supported.
- [ ] Multiple subpasses within a render pass don't display full information.
- [ ] Secondary command buffers don't produce full information.

## Environment

* RenderDoc version: v1.9 or later stable build
* Operating System: Windows, Linux, Android
* Graphics API: Vulkan

**Comment by ishitatsuyuki** [comment]
I'm running 1.9 and the PixelHistory config doesn't seem to exist; also pixel history seems to work to some extent on Vulkan. If then, is this issue obsolete?

**Comment by baldurk** [comment]
Yes as noted in the 1.9 release notes, pixel history has been released as stable. This issue still exists to track further work to expand support, which is why it hasn't been closed.

**Comment by athanase** [comment]
Hello, I don't have any PixelContext window, and no options to display it.
I might have missed something (I activated "ShaderDebugging" and "PixelHistory" in the Core settings) ?

### Environment
- RenderDoc version: v1.10
- Graphics API: Vulkan 1.2.153
- GPU Driver: Nvidia driver 455.28 
- GPU: GeForce GTX 1070 Ti
- Operating System: Linux 5.9.2-arch1-1

**Comment by baldurk** [comment]
The texture viewer layout is customisable, perhaps you docked the pixel context panel somewhere other than where it is by default. Can you share a screenshot of your texture viewer?

The shader debugging and pixel history settings have been removed and are not used for anything, which is why they are not mentioned or documented anywhere. If you hover over those settings the tooltip will also say that they are unused.

**Comment by athanase** [comment]
Here you go. I am a new user with this awesome tool so I might be missing it.

![image](https://user-images.githubusercontent.com/1231368/98485890-1020a100-221a-11eb-9552-538845757be5.png)

**Comment by baldurk** [comment]
Looks like it really is missing somehow. The inputs and outputs tabs have been split up so maybe the docking state got confused somewhere. If you close the texture viewer and re-open it, that should reset it to default and the context will be visible.

**Comment by athanase** [comment]
It worked. Thanks very much !

**Comment by luc4s** [comment]
Hello,
I don't know if it is related, but I have a render pass with a few subpasses and input attachments, and pixel debug feature does not work properly (seems like it cannot load from input attachments).
Is this related to `Multiple subpasses within a render pass don't display full information.` ?

**Comment by baldurk** [comment]
Please don't comment on unrelated issues with your problems. If you have a bug report create it as a new issue, this issue is clearly marked as tracking pixel history status.

**Comment by baldurk** [comment]
Closing as these tracking issues can confuse people (see above) and should not be used as a catch-all for bug reporting on these features. The issues were only really relevant when the features were first released and in beta.
